# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache: pip
python:
  - "3.7"
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis codecov

# Command to run tests, e.g. python setup.py test
script:
  - tox

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# If your project is built on travis-ci.org you can use
# $ travis encrypt your-password-here --add deploy.password
# Or just use this website:
# Repository name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
# http://rkh.github.io/travis-encrypt/public/index.html
# If your project is built on travis-ci.com you can use
# $ travis encrypt your-password-here --add deploy.password --com
#
# Details here:
# https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    # To limit who can create releases, see how to set branch protection here:
    # https://help.github.com/en/articles/configuring-protected-branches 
    branch: stable
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    python: 3.7
{%- endif %}
