name: Build Example Repo

on:
  push:
    branches:
      - master
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 18:00:00 UTC (Monday at 10:00:00 PST)
    - cron: '0 18 * * 1'

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip install cookiecutter
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
        rm -Rf python_boilerplate/.github/workflows/
    - name: Install Generated Repo Dependencies
      run: |
        pip install -e python_boilerplate[all]
    - name: Run Generated Repo Tests
      run: |
        pytest python_boilerplate/python_boilerplate/tests/
    - name: Publish Repo
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: 'example-build' # The branch the action should deploy to.
        FOLDER: python_boilerplate/ # The folder the action should deploy
        CLEAN: true
    - name: Test Generate Docs
      run: |
        cd python_boilerplate
        make gen-docs
        touch docs/_build/html/.nojekyll
