name: Test Repo Construction

on:
  pull_request:
    branches:
      - master

jobs:
  test-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Generate Example Repo
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: ${{ github.head_ref }} # The branch the action should deploy from.
        BRANCH: 'test-build' # The branch the action should deploy to.
        FOLDER: python_boilerplate # The folder the action should deploy.
        BUILD_SCRIPT: pip install cookiecutter && mv python_boilerplate/.git/ temp/ && rm -Rf python_boilerplate && cookiecutter gh:AllenCellModeling/cookiecutter-pypackage --no-input && rm -Rf python_boilerplate/.github/workflows/ && mv temp/ python_boilerplate/.git/

    - name: Generate Example Docs
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: 'test-build' # The branch the action should deploy from.
        BRANCH: 'test-docs' # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy. This example folder is generated by Sphinx
        BUILD_SCRIPT: pip install -e .[dev] && make gen-docs && touch docs/_build/html/.nojekyll # The build script the action should run prior to deploying.

    - name: Switch to test-build Branch
      run: |
        git branch --set-upstream-to=origin/test-build test-build
        git pull

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Lint with flake8
      run: |
        flake8 python_boilerplate --count --verbose --max-line-length=127 --show-source --statistics

    - name: Test with pytest
      run: |
        pytest python_boilerplate/tests/
